# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uniques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=16, unique=True)),
                ('field2', models.CharField(max_length=16, unique=True)),
                ('field3', models.CharField(max_length=16)),
                ('field4', models.CharField(default=b'default_value', max_length=16)),
                ('field5', models.CharField(default=None, max_length=16, null=True)),
                ('field6', models.CharField(max_length=16)),
                ('field7', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='uniques',
            unique_together=set([('field6', 'field7')]),
        ),
    ]
